### ISSUE TITLE
github.com/lios/go-activiti/engine/behavior好多方法找不到

### ISSUE THREAD

**Issue by Lewis-liuwei** [lios/go-activiti#2]
GetDefineManager not declared by package behavior

**Comment by forestli120511830** [comment]
defineManager := behavior.GetDefineManager()   修改为   defineManager := manager.GetDefineManager()

**Comment by Lewis-liuwei** [comment]
好的，谢谢

**Comment by Lewis-liuwei** [comment]
> ```
> defineManager := behavior.GetDefineManager()   修改为   defineManager := manager.GetDefineManager()
> ```
